spring:
  profiles:
    active: dev
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.38.162:3306/user?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.38.162:8848
server:
  port: 8804
mybatis-plus:
  mapper-locations: classpath:com/liuxun/user/mapper/xml/*.xml



#  config:
#    type: nacos
#    nacos:
#      server-addr: 192.168.38.162:8848
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 192.168.38.162:8848
#      # 服务名,与服务端中registry.conf配置要一致
#      application: seata-server
#  tx-service-group: mail_tx_group
#  service:
#    vgroup-mapping:
#      mail_tx_group: "default"
