spring:
  profiles:
    active: dev
  application:
    name: service1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.38.162:3306/service1
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.38.162:8848
mybatis:
  mapper-locations: classpath:com/liuxun/service1/mapper/xml/*.xml
server:
  port: 8801
